<a href="https://colab.research.google.com/github/herdinsavira/AI/blob/main/AI_JOBSHEET_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**JOBSHEET 2 - Operasi Matematika, Vektor, dan Matriks**

**LATIHAN**

1. Tipe Data Python

In [ ]:
# a. Cek Type Data
var = 123
print(type(var))

<class 'int'>


In [ ]:
# b. Tipe Data String
a = '123'
b = '3.4'
c = "Data String"

print(type(c))

<class 'str'>


In [ ]:
# c. Tipe Data Numerik
var1 = 345
var2 = 34.5

f1 = float(var1)
print(type(f1))
print(f1)

jumlah = var1 + var2
print(jumlah)

var3 = 12.3
var4 = 12.9

i1 = int(var2)
i2 = int(var3)

print(i1)
print(i2)

<class 'float'>
345.0
379.5
34
12


In [ ]:
# d. Tipe Data Boolean
var1 = 345
var2 = 34.5

print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


In [ ]:
# e. Tipe Data List
data = ["belajar dasar python", 2023, 3.8, True]

print(data)
print(data[3])
print(data[1:3])
print(len(data))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


2. Operasi Matematika Python

In [ ]:
# Nilai Minimum dan Maksimum
x = min(5, 10, 25)
y = max(6, 12, 18)

print(x)
print(y)

5
18


In [ ]:
# Nilai Absolut
x = abs(-7.25)
print(x)

7.25


In [ ]:
# Pangkat
import math

x = math.pow(4,3)
print(x)

64.0


In [ ]:
# Akar
import math

x = math.sqrt(64)
print(x)

8.0


In [ ]:
#Pembulatan
import math

x = math.ceil(1.4)
y = math.floor(1.4)

print(x)
print(y)

2
1


In [ ]:
# Nilai Konstanta PI
import math

x = math.pi
print(x)

3.141592653589793


3. Operasi MAtriks dan Vektor

In [ ]:
# Penjumlahan Matriks
import numpy as np

A = np.array([[80,30,25],
              [50,20,10]])

B = np.array([[30,60,15],
              [10,30,30]])

hasil = A + B

print(hasil)

[[110  90  40]
 [ 60  50  40]]


In [ ]:
#Dot Product
import numpy as np

A = np.array([10,20,15])
B = np.array([16,67,35])

hasil = np.dot(A,B)

print(hasil)

2025


In [ ]:
# Cross Product
import numpy as np

A = np.array([10,20,15])
B = np.array([16,67,35])

hasil = np.cross(A,B)

print(hasil)

[-305 -110  350]


**TUGAS PARAKTIKUM**

In [ ]:
# 1. Perkalian Matriks
import numpy as np

A = np.array([[3,1],
              [2,0]])

B = np.array([[2,1],
              [1,-1]])

C = np.array([[-1,1,2],
              [2,0,-1]])

# A x B
hasil_AB = np.dot(A,B)

# B . C
hasil_BC = np.dot(B,C)

print("Hasil A x B =")
print(hasil_AB)

print("\nHasil B . C =")
print(hasil_BC)

Hasil A x B =
[[7 2]
 [4 2]]

Hasil B . C =
[[ 0  2  3]
 [-3  1  3]]


In [ ]:
# 2. Faktorial
import math

# 6!
f1 = math.factorial(6)

# 8! / 5!
f2 = math.factorial(8) / math.factorial(5)

print("6! =", f1)
print("8! / 5! =", f2)

6! = 720
8! / 5! = 336.0


In [ ]:
# 3. Operasi Vektor
import numpy as np

A = np.array([5,3,7])
B = np.array([12,-3,1])

# Panjang vektor
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Dot product
dot_AB = np.dot(A,B)

# Cross product
cross_AB = np.cross(A,B)

print("Panjang Vektor A =", panjang_A)
print("Panjang Vektor B =", panjang_B)

print("A . B =", dot_AB)

print("A x B =", cross_AB)

Panjang Vektor A = 9.1104335791443
Panjang Vektor B = 12.409673645990857
A . B = 58
A x B = [ 24  79 -51]
